# Generated by Django 5.1.3 on 2025-01-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RopaHombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('enlace', models.URLField()),
                ('precio', models.CharField(max_length=100)),
                ('precio_original', models.CharField(blank=True, max_length=100, null=True)),
                ('descuento', models.CharField(blank=True, max_length=100, null=True)),
                ('tallas', models.TextField()),
            ],
        ),
    ]
