# Generated by Django 5.1.3 on 2025-01-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denominacion',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='vino',
            name='denominacion',
        ),
        migrations.RemoveField(
            model_name='vino',
            name='uvas',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Denominacion',
        ),
        migrations.DeleteModel(
            name='Uva',
        ),
        migrations.DeleteModel(
            name='Vino',
        ),
    ]
