# Generated by Django 5.1.3 on 2025-01-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_denominacion_pais_remove_vino_denominacion_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ropahombre',
            index=models.Index(fields=['precio'], name='main_ropaho_precio_e4f62d_idx'),
        ),
    ]
